#pragma once

#include <stdint.h>
#include <stddef.h>

/**
 * @brief I2S audio output configuration.
 */
typedef struct {
    int pin_din;
    int pin_bclk;
    int pin_lrc;
    int sample_rate;
} audio_config_t;

/**
 * @brief Initialize the I2S peripheral for audio output.
 */
void audio_init(const audio_config_t *config);

/**
 * @brief Write raw 16-bit PCM samples to I2S. Blocks until all are sent.
 *
 * @param data  16-bit signed PCM samples.
 * @param len   Number of bytes (not samples).
 */
void audio_write(const int16_t *data, size_t len);

/**
 * @brief Play a sine wave tone. Useful for testing the hardware.
 */
void audio_play_tone(uint16_t freq_hz, uint32_t duration_ms, float volume);

/**
 * @brief Play a raw PCM clip generated by mp3toc.py.
 *
 * @param data        int16_t sample array.
 * @param num_samples Number of samples (not bytes).
 */
void audio_play_pcm(const int16_t *data, size_t num_samples);

/* -----------------------------------------------------------------------
 * Streaming MP3 decoder
 *
 * Usage:
 *   audio_mp3_stream_t stream;
 *   audio_mp3_stream_init(&stream);
 *   // for each TCP chunk:
 *   audio_mp3_stream_feed(&stream, data, len);
 *   // when connection closes:
 *   audio_mp3_stream_flush(&stream);
 * ----------------------------------------------------------------------- */

/* Input ring buffer -- must be larger than the largest MP3 frame (~1.5 KB) */
#define AUDIO_MP3_IN_BUF_SIZE  (16 * 1024)

/* Forward-declare the minimp3 type without pulling in the full header here */
typedef struct audio_mp3_stream audio_mp3_stream_t;

audio_mp3_stream_t *audio_mp3_stream_alloc(void);
void                audio_mp3_stream_free(audio_mp3_stream_t *s);

/**
 * @brief Reset the stream decoder state. Call before a new MP3 starts.
 */
void audio_mp3_stream_init(audio_mp3_stream_t *s);

/**
 * @brief Feed incoming bytes into the decoder.
 *        Decodes and plays any complete MP3 frames found in the buffer.
 */
void audio_mp3_stream_feed(audio_mp3_stream_t *s, const uint8_t *data, size_t len);

/**
 * @brief Flush any remaining buffered data. Call when the TCP connection closes.
 */
void audio_mp3_stream_flush(audio_mp3_stream_t *s);
